export const CATEGORIES = [
  {
    icon: "🎮",
    tag: "Games",
    name: "Games",
    examples: "Snake, Tetris, Pong, Space Invaders, Maze Solver, Sudoku Solver, Hoops, PhotoBomb",
    langs: ["Python", "JavaScript"],
    cat: "cat-games",
  },
  {
    icon: "🌐",
    tag: "Web",
    name: "Web",
    examples: "Portfolio site, Weather dashboard, Music visualiser, News aggregator, Real-time tools",
    langs: ["HTML", "CSS", "JavaScript"],
    cat: "cat-web",
  },
  {
    icon: "🤖",
    tag: "AI",
    name: "AI",
    examples: "AI study buddy, Image classifier, Voice assistant, AI-powered chatbot",
    langs: ["Python", "JavaScript"],
    cat: "cat-ai",
  },
  {
    icon: "📊",
    tag: "Data",
    name: "Data",
    examples: "Spotify stats, Fitness tracker, Live data pipeline, Timetable analyser",
    langs: ["Python", "JavaScript"],
    cat: "cat-data",
  },
  {
    icon: "⚙️",
    tag: "Hardware",
    name: "Hardware",
    examples: "Smart traffic light, Room environment monitor, Line-following robot",
    langs: ["Python"],
    cat: "cat-hardware",
  },
  {
    icon: "🛠️",
    tag: "Tools",
    name: "Tools",
    examples: "Password manager, Markdown editor, Personal API, Productivity app",
    langs: ["Python", "JavaScript"],
    cat: "cat-tools",
  },
];
